[package]
name = "distmesh"
version = "0.1.0"
edition = "2021"
authors = ["BZoennchen <benedikt.zoennchen@web.de>"]

[dependencies]
delaunator = "1.0.2"
rand = "0.8"
nannou = "0.19.0"
robust = "1.1.0"